env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 1
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-useless-escape:
    - off
  no-self-assign:
    - off
  no-empty:
    - off
  no-pattern:
    - off
  no-fallthrough:
    - off
  no-case-declarations:
    - off
  no-empty-pattern:
    - off
  "@typescript-eslint/no-empty-function":
    - off
  "@typescript-eslint/no-non-null-assertion":
    - off
  "@typescript-eslint/no-empty-interface":
    - off
  "@typescript-eslint/adjacent-overload-signatures":
    - off
  "@typescript-eslint/no-namespace":
    - off
  "@typescript-eslint/explicit-module-boundary-types":
    - off
  "@typescript-eslint/no-explicit-any":
    - off
  "@typescript-eslint/no-var-requires":
    - off
  "@typescript-eslint/ban-types":
    - warn
